---
- name: Log in (obtain access token)
  k8s_auth:
    host: "{{ k8s_auth_host }}"
    validate_certs: False
    username: "{{ k8s_username }}"
    password: "{{ k8s_password }}"
  register: k8s_auth_results
  when: k8s_username != ""

- name: set auth api key if username/password is provided
  set_fact:
    k8s_auth_api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
  when: k8s_auth_results.k8s_auth is defined

